"""Add activity reward system

Revision ID: 28867054fe10
Revises: None
Create Date: 2026-05-29 11:21:55.928633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '28867054fe10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_reward_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_reward_history', 'reward_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('activity_reward_history', 'claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.core.database.SafeDateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_reward_history_task_id'), table_name='activity_reward_history')
    op.drop_constraint(op.f('activity_reward_history_task_id_fkey'), 'activity_reward_history', type_='foreignkey')
    op.create_foreign_key(None, 'activity_reward_history', 'activity_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('activity_tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('activity_tasks', 'target_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'reward_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.execute("ALTER TABLE activity_tasks ALTER COLUMN activity_type TYPE activitytype USING activity_type::activitytype")
    op.alter_column('activity_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.core.database.SafeDateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.core.database.SafeDateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_tasks_activity_type'), table_name='activity_tasks')
    op.drop_index(op.f('ix_activity_tasks_is_active'), table_name='activity_tasks')
    op.alter_column('user_activity_progress', 'current_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('user_activity_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.core.database.SafeDateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_activity_progress_claimed'), table_name='user_activity_progress')
    op.drop_index(op.f('ix_user_activity_progress_completed'), table_name='user_activity_progress')
    op.drop_constraint(op.f('uq_user_activity_task'), 'user_activity_progress', type_='unique')
    op.drop_column('user_activity_progress', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity_progress', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_activity_task'), 'user_activity_progress', ['user_id', 'task_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_activity_progress_completed'), 'user_activity_progress', ['completed'], unique=False)
    op.create_index(op.f('ix_user_activity_progress_claimed'), 'user_activity_progress', ['claimed'], unique=False)
    op.alter_column('user_activity_progress', 'updated_at',
               existing_type=app.core.database.SafeDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_activity_progress', 'current_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_activity_tasks_is_active'), 'activity_tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_activity_tasks_activity_type'), 'activity_tasks', ['activity_type'], unique=False)
    op.alter_column('activity_tasks', 'updated_at',
               existing_type=app.core.database.SafeDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'created_at',
               existing_type=app.core.database.SafeDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'activity_type',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='activitytype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'reward_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'target_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('activity_tasks', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'activity_reward_history', type_='foreignkey')
    op.create_foreign_key(op.f('activity_reward_history_task_id_fkey'), 'activity_reward_history', 'activity_tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_activity_reward_history_task_id'), 'activity_reward_history', ['task_id'], unique=False)
    op.alter_column('activity_reward_history', 'claimed_at',
               existing_type=app.core.database.SafeDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('activity_reward_history', 'reward_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('activity_reward_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
