"""Add invitation bonus system

Revision ID: dadce8247c9f
Revises: 28867054fe10
Create Date: 2026-05-29 12:11:32.990895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadce8247c9f'
down_revision: Union[str, None] = '28867054fe10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('first_deposit_amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('referrals', sa.Column('first_deposit_completed', sa.Boolean(), nullable=False))
    op.add_column('referrals', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'status')
    op.drop_column('referrals', 'first_deposit_completed')
    op.drop_column('referrals', 'first_deposit_amount')
    # ### end Alembic commands ###
