"""Add First Gift

Revision ID: f07d8511db86
Revises: d58a1f88059c
Create Date: 2026-05-29 15:19:26.233524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07d8511db86'
down_revision: Union[str, None] = 'd58a1f88059c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_gift_claims',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_claimed', sa.Float(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('first_gift_claims')
    # ### end Alembic commands ###
